# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
docker:
  - image: circleci/node:10
working_directory: ~/repo
jobs:
  build:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    - run: yarn test:coveralls
  sonarbranch:
    - run: yarn sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.branch.name=${CIRCLE_BRANCH} -Dsonar.branch.target=master
  sonar:
    - run: yarn sonar-scanner -Dsonar.login=${SONAR_TOKEN}
  docs:
    - run: yarn docs:deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        requires:
          - build
      - sonarbranch
        requires:
          - test
        filters:
          branches:
            ignore: master
      - sonar
        requires:
          - test
        filters:
          branches:
            only: master
      - docs
        requires:
          - test
        filters:
          branches:
            only: master
